version: "3"

services:
    mindmap-backend:
        container_name: "mindmap-backend"
         image: "mindmap-backend:1.0.0"
         stdin_open: true
         network_mode: host
         command:
            npm start
         ports:
            - "4334:4334"
     

    mindmap-frontend:
        container_name: "mindmap-frontend"
        image: "mindmap-frontend:1.0.0"
        stdin_open: true
        network_mode: host
        tty: true
        command:
            npm start
        ports:
            - "4000:4000"
        depends_on:
            - "mindmap-backend"
