FROM node:12.16.3

WORKDIR /usr/frontend-nextjs

COPY package*.json ./
RUN npm install

COPY . .

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "vim"]

EXPOSE 3001
CMD [ "npm", "run", "start" ]